### PR TITLE
update urllib to latest

### PR DESCRIPTION
**Pull request by hemanthrough**
bumping urllib due to https://github.com/advisories/GHSA-g4mx-q9vg-27p4

### CODE REVIEW

**Comment by pyrooka** [comment]
Hi! Thanks for your contribution, but we would like to avoid upgrading to the next major version (v2) at the moment. 
As I can see, the CVE got fixed in `1.26.18` too, so maybe all we need to do is replacing the minimum version with that.

**Comment by hemanthrough** [comment]
@pyrooka sure will do that 
is there any reason for not doing that ?

**Comment by pyrooka** [comment]
Well, we plan to do it in the near future, but we have other projects that also need to be updated and we would like to do it in one batch. So the main reason is our internal tracking and to keep these projects in sync.

**Comment by hemanthrough** [comment]
ok thanks.
I suppose you will take it from here :) ? (wrt to travis and stuff) 
Should I do anything else ?

**Comment by padamstx** [comment]
Closing this PR and opened [this PR](https://github.com/IBM/python-sdk-core/pull/180) due to Travis issues.

**Pull request closed without merging**
