### PR TITLE
feat: define new BaseService.configure_service function

### PR DESCRIPTION
**Pull request by padamstx**
This commit only changes the README.md file, but the main purpose of the
commit is to provide a commit that is friendly to semantic-release that will
describe the latest set of commits that were inadvertently merged into master
without squashing.

### CODE REVIEW

**Comment by padamstx** [comment]
cc: @mgrattray

**Comment by ehdsouza** [comment]
How about a empty commit? git commit --allow-empty -m <your message>

**Comment by ehdsouza** [comment]
How about a empty commit? `git commit --allow-empty -m <your message>`

**Comment by padamstx** [comment]
lol

**Comment by padamstx** [comment]
did a force push of an empty commit

**Pull request merged**
